version: "3.8"

volumes:
  test_pg_data:

services:
  postgres:
    container_name: pg_test_container
    image: postgres:11.16-alpine
    volumes:
      - "test_pg_data:/var/lib/postgresql/data"
    restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: go-micro-template