version: '3'

volumes:
  pg_data:

services:
  postgres:
    container_name: pg_db_auth_service
    image: postgres:11.16-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: auth_service
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d auth_service"]
      interval: 5s
      timeout: 10s
      retries: 5

  migrate:
    image: migrate/migrate:v4.16.2
    env_file:
      - ../envs/.env
    volumes:
      - ../db/migrations:/migrations
      - ../db/fixtures:/fixtures
    command: [
      "-path",
      "/migrations",
      "-database",
      "postgres://admin:admin@postgres:5432/auth_service?sslmode=disable",
      "up"
    ]
    depends_on:
      postgres:
        condition: service_healthy

  data_loader:
    build:
      context: ..
      dockerfile: deployments/Dockerfile.load
    container_name: pg_db_auth_service_data_loader
    volumes:
      - ../db/fixtures:/app/db/fixtures
    environment:
      - ENV=development
    command: ["load_data"]
    depends_on:
      migrate:
        condition: service_completed_successfully

  app:
    build:
      context: ..
      dockerfile: deployments/Dockerfile
    container_name: auth_service
    ports:
      - "8080:8080"
    environment:
      - ENV=development
    command: ["serve"]
    depends_on:
      data_loader:
        condition: service_completed_successfully