CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE users (
"id" uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
"username" VARCHAR(254) UNIQUE NOT NULL,
"password" VARCHAR(60) NOT NULL,
"created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
"updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
"deleted_at" TIMESTAMP WITH TIME ZONE DEFAULT NULL
);
